package Interactions;

import javax.swing.*;
import java.awt.*;
import java.awt.image.BufferedImage;

//this is teh panel that chows the image generated by the rey tracing program
public class ResultPanel extends JPanel {
    private final BufferedImage image;

    //constructor
    public ResultPanel(BufferedImage image) {
        this.image = image;

        int height = image.getHeight();
        int width = image.getWidth();
        this.setSize(width, height);
        this.setVisible(true);
    }

    //override for the painter to paint the image
    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        try{
            g.drawImage(image, 0, 0, this);
        }catch (Exception e){
        }

    }
}
